### ISSUE TITLE
Mobility of Nodes in PlanetSim

### ISSUE THREAD

**Issue by hha00m** [jpahullo/planetsim#1]
In ordered to make the nodes have the ability to move, you suggested that companied this simulation with another simulation supported such as NS-2 but would you please give me an example about how to do that because we develop this simulation but I need giving the nodes an ability to move around.
I am looking forward to hearing from you.

**Comment by jpahullo** [comment]
At sourceforge.net there are contributions that built a location-aware simulated networks, including even latency. They can help you in some way.

Based exclusively on this project,  you need to design a process to decide which nodes to move around the network at every single simulation step. You should modify planetsim core, since it is not extensible this way.

Hoping that helps.

**Comment by hha00m** [comment]
Many Thanks

**Comment by jpahullo** [comment]
You're welcome. Thanks for your interest.
